parameters:
  serviceConnection: ''
  acrName: ''
  aksResourceGroup: ''
  aksCluster: ''
  chartName: ''
  chartReleaseName: ''
  chartNamespace: ''
  testPodName: ''

jobs:
- job: ValidateChart
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.11.0'
      installKubectl: false

  - task: AzureCLI@1
    displayName: 'AKS Authenticate'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks get-credentials --resource-group ${{ parameters.aksResourceGroup }} --name ${{ parameters.aksCluster }}

  - template: ../../tasks/charts/cleanup.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksCluster: ${{ parameters.aksCluster }}
      chartReleaseName: ${{ parameters.chartReleaseName }}
      chartNamespace: ${{ parameters.chartNamespace }}
      testPodName: ${{ parameters.testPodName }}

  - task: AzureCLI@1
    displayName: 'Lint and Test'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks get-credentials --resource-group ${{ parameters.aksResourceGroup }} --name ${{ parameters.aksCluster }}
        helm lint ${{ parameters.chartName }}
        helm install ${{ parameters.chartName }} --name ${{ parameters.chartReleaseName }} --namespace ${{ parameters.chartNamespace }} --wait
        helm test ${{ parameters.chartReleaseName }}

  - template: ../../tasks/charts/cleanup.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksCluster: ${{ parameters.aksCluster }}
      chartReleaseName: ${{ parameters.chartReleaseName }}
      chartNamespace: ${{ parameters.chartNamespace }}
      testPodName: ${{ parameters.testPodName }}
