parameters:
  serviceConnection: 'azurerm-nonprod'
  aksResourceGroup: 'cnp-aks-rg'
  aksCluster: 'cnp-aks-cluster'
  chartName: ''
  chartReleaseName: ''
  chartNamespace: ''

jobs:
- job: ValidateChart
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.11.0'
      installKubectl: false

  - task: AzureCLI@1
    displayName: 'Lint and Test'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks get-credentials --resource-group ${{ parameters.aksResourceGroup }} --name ${{ parameters.aksCluster }}
        helm lint ${{ parameters.chartName }}
        helm install ${{ parameters.chartName }} --name ${{ parameters.chartReleaseName }} --namespace ${{ parameters.chartNamespace }} --wait
        helm test ${{ parameters.chartReleaseName }} --cleanup

  - task: AzureCLI@1
    displayName: 'Delete Test Chart'
    continueOnError: true
    condition: always()
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptLocation: 'inlineScript'
      inlineScript: helm delete --purge ${{ parameters.chartReleaseName }}
