parameters:
  testUrl: ''
  maxAttempts: ''
  sleepTime: ''

steps:
- task: CmdLine@2
  displayName: Health Check
  env:
    TEST_URL: ${{ parameters.testUrl }}
    MAX_ATTEMPTS: ${{ parameters.maxAttempts }}
    SLEEP_TIME: ${{ parameters.sleepTime }}
  inputs:
    script: |
      #!/bin/bash
      attempts=1

      printf "Trying $TEST_URL\n"
      while (( attempts <= $MAX_ATTEMPTS ))
      do
        printf "Attempt #$attempts\n"
        response=`curl -sk -o /dev/null -w "%{http_code}" $TEST_URL`
        ((attempts++))

        if (( response >= 200 && response <= 399 )); then
          printf "Service is healthy, returned HTTP $response\n"
          exit 0
        else
          printf "Returned HTTP $response, retrying...\n"
          sleep $SLEEP_TIME
        fi
      done

      printf "Service not healthy, giving up.\n"
      exit 1