parameters:
  serviceConnection: ''

jobs:
- job: TerminateAgent
  dependsOn: JavaBuild
  pool:
    name: 'Hosted Ubuntu 1604'

  steps:
  - checkout: none

  - template: ../steps/configure-helm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}

  - task: HelmDeploy@0
    displayName: 'Delete Agent'
    enabled: true
    inputs:
      connectionType: $(kubectlConnectionType)
      azureSubscription: ${{ parameters.serviceConnection }}
      azureResourceGroup: $(aksResourceGroup)
      kubernetesCluster: $(clusterName)
      command: 'delete'
      arguments: '--purge $(agentName)'